### PR TITLE
Update example HTML file

### PR DESCRIPTION
**Pull request by lachlanjc**
This PR updates the example `index.html` file, linking `bundle.js` instead of `dev.js` and adding `<html>`/`<body>` tags. If you don’t want the HTML skeleton, the first commit only fixes the script path.

### CODE REVIEW

**Comment by jxnblk** [comment]
Thanks! I think I'd prefer to keep the example at the bare minimum so it's easier to see what's essential to get going.

**Comment by lachlanjc** [comment]
Got it got it. Will push in just a sec.

**Comment by lachlanjc** [comment]
Yo! Totally understand that. Does this look better?

Personally, I think it’s best to have the `<html>`/`<body>` elements for beginners — it’s not hard to know for experienced devs they can add those things in, but it could be confusing otherwise. If you’d like to keep it _super_ simple, we can remove even the body, but we should make sure to link to `bundle.js`.

**Comment by lachlanjc** [comment]
(If you do merge this, you’ll probably want to exercise the “squash + merge” option :wink:)

**Pull request closed without merging**
